### ISSUE TITLE
Sticky "download complete" notification after app closes [hibiki]

### ISSUE THREAD

**Issue by RobbWatershed** [RobbWatershed/Hentoid#18]
Download a book from nhentai
Wait for it finish
Close the app
Then open it again

**Comment by assintates** [comment]
this issue is still there on latest debug build.

**Comment by RobbWatershed** [comment]
Should have been fixed by 6701a6cda0136baad85d6cc932f3036659452544

**Comment by RobbWatershed** [comment]
Fix confirmed
