### ISSUE TITLE
Memory leaks when exiting webviews

### ISSUE THREAD

**Issue by RobbWatershed** [RobbWatershed/Hentoid#69]
CAN BE REPRODUCED ON DEBUG RELEASES ONLY

1. Use a webview to browse a site
2. Go to a book page and use the "Download" floating action button
3. Go back to library screen using the "Memory chip" floating action button
4. Go to the queue screen
5. Wait until the download is complete

Expected : Nothing specific happens
Actual : Canary app reports a memory leak

Confirmed on :
NHentai
Hitomi
Hentai Cafe
E-hentai
Pururin
Tsumino
ASM Hentai

**Comment by herdidi47** [comment]
go back using back button or the fab?

**Comment by RobbWatershed** [comment]
Might be related to https://stackoverflow.com/questions/3130654/memory-leak-in-webview

**Comment by RobbWatershed** [comment]
Fixed in 11ff0fa24232a116125549e87aa564c48b559b0f

**Comment by RobbWatershed** [comment]
truncating is not working, i tried selecting both 160 and 200 and it resulted in the name folder name and also both folder had the same name with a length of 278

deep_valley - Inkou_Kyoushi_no_Saimin_Seikatsu_Shidouroku_Sensei...Kare_no_Tame_ni_Watashi_no_Shojomaku__Kantsuu_ShiteKudasai - [246450]
that's all in the same line but even discord can't handle deep valley names lol

**Comment by RobbWatershed** [comment]
Leak downloading from e-hentai

**Comment by RobbWatershed** [comment]
Fix attempt in 36821a6d0c29630ee702cfb8e2aa1f275db7a8ea

**Comment by RobbWatershed** [comment]
This issue was moved to avluis/Hentoid#209
