### ISSUE TITLE
Clearing library/mikan search is not intuitive for users right now.

### ISSUE THREAD

**Issue by ArturRA** [RobbWatershed/Hentoid#73]
Right now it's not very intuitive how to clear a search in library/mikan which shouldn't happen.
There is also the fact that since you need to click the magnifier to clear search and click the back button in the end the flow ends up like this:
1.Current flow:Click mangfier with "!", and then since the keyboard will pop-up you then need to click the back key button
2.Suggested flow:Click clear button(or the back button, but again I gave up on that) and boom you cleared the search and is back to library view
In the videos below the behavior is reproduced.
https://cdn.discordapp.com/attachments/490202301663936512/494007189472542720/20180925_014711.mp4

https://cdn.discordapp.com/attachments/490202301663936512/494007792332439563/20180925_014937.mp4

**Comment by wightwulf1944** [comment]
I propose expected result should be:

when results are shown, a 48dp height banner should be shown below the toolbar with a "clear" button and text "showing X results"

**Comment by RobbWatershed** [comment]
This issue was moved to avluis/Hentoid#185
